### ISSUE TITLE
Firefox returning inverted numbers

### ISSUE THREAD

**Issue by hectorcarranza** [d4nyll/lethargy#1]
Hi. 

Let me tell you've done a great job with this code. It works like a charm.

But there is a little problem when using it on firefox.

Chrome and Safari return -1 when going down and 1 when going up (expected behaviour) while Mozilla's browser does the opposite.

Hardware: Macbook Air
SO: OSX Yosemite
Using Firefox 37.0.2

I can solve this by using browser detection but maybe there is a simpler way to fix it from lethargy.js.

PD: I'm still learning to write in english.

**Comment by d4nyll** [comment]
Thanks for the compliment, really appreciate it! I was very rushed when I wrote it, so this issue is probably a typo of mine.

Firefox binds to a different event - [`DOMMouseScroll`](https://developer.mozilla.org/en-US/docs/Web/Events/DOMMouseScroll) in older versions and [`wheel`](https://developer.mozilla.org/en-US/docs/Web/Events/wheel) in newer versions. For `DOMMouseScroll`, we check it's delta value via `e.originalEvent.detail`, which has the opposite sign to `wheelDelta` events. As you can see on [line 46](https://github.com/d4nyll/lethargy/blob/master/lethargy.js#L46), I should probably have multiplied it by `-40` instead of `40`.

I will check that tomorrow. Maybe you can try it out as well and tell me your findings as well!?

Again, thanks for raising the issue, and thanks for using lethargy!

**Comment by d4nyll** [comment]
Fixed with 3a7f6bd

**Comment by hectorcarranza** [comment]
I updated the code and now it works in Firefox without any browser check. It's perfect.

You have saved me tons of kilobytes with lethargy. I'm replacing jquery.mousewheel with lethargy for a slideshow like website I'm working on. I'll send you the URL when it goes live.

PD: did I mentioned I spend 3 days trying to normalize trackpad scroll in a mac? I was about to give up until I found this code.

Thanks a lot.

**Comment by d4nyll** [comment]
@hectorcarranza Thank you for your kind words! If you are doing a slideshow-like website, you may want to consider [smartscroll](https://github.com/d4nyll/smartscroll), a jQuery plugin I wrote which does exactly that. The performance isn't too good right now, but I plan to refactor the code when I have the time. Please do try that out and see what you think!
